name: flutter_translate_codegen_annotations
description: Defines the annotations used by flutter_translate_codegen to create statically-typed localization keys.
version: 1.0.0
homepage: https://www.swypex.com
repository: https://github.com/bratan/flutter_translate_codegen_annotations

environment:
  sdk: '>=2.12.0 <3.0.0'
